version: "2.1"

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./api:/usr/src/api
        restart: on-failure
        environment:
            - DB_HOST=db
            - DB_NAME=recommerce
            - DB_USER=root
            - DB_PASSWORD=root
        depends_on:
            - db

    db:
        image: mariadb:10.1
        restart: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=recommerce

    nginx:
        image: nginx:latest
        ports:
            - "8000:8000"
        volumes:
            - ./api:/usr/src/api
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: on-failure
        depends_on:
            - php
    
    adminer:
        image: adminer
        restart: always
        ports: 
            - "8080:8080"