App\Entity\Product:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 200
      nullable: false
    price:
      type: float
      nullable: false
  manyToOne:
    brand:
      targetEntity: App\Entity\Brand
      joinColumn:
        nullable: false